print("hello world")
print ('hello world ')
print ("hi this is test \n how are you?")
ans = input("what is your name?")
print ("hi how are you doing? "+ ans)
print (3+5)
print (5-3)
print (3*5)
print (3/5)